### ISSUE TITLE
[Feature Request] - Package 'eth-sig-util' as a browser component

### ISSUE THREAD

**Issue by xmaysonnave** [MetaMask/eth-sig-util#100]
Starting from th v8.0.x, Metamask-extension is able to provide a public encryption key and to decrypt content.

I tried to dynamically load the library in my browser DApp from:
https://cdn.jsdelivr.net/npm/eth-sig-util@2.5.3/index.min.js
However it appears that this package is not build as a browser friendly component (nodejs).

In my build chain I need to clone, browserified, tercerified and embed this library in my DApp in order to encrypt content with the Metamask provided public encryption key. Roughly 400KB.

Do you have any plan to package this component as a browser friendly component ?

Thanks

**Comment by markg85** [comment]
I totally second this! (or eight based on the thumbs up).

I too was about to attempt to use this package in a browser. There are instructions for NPM/yarn (though it breaks on npm at the moment #227). But besides that, i very much like to **just** have a browser package. Not a monsterified bundle package of half a megabyte.

I personally find those bundle things very destructive for the web and specifically for CDN's. Their existence is to serve common libraries. If each site bundles it's whole js stack in one gigantic bundle then the purpose of CDN's becomes 0.

**Comment by mcmire** [comment]
We have no immediate plans to do this but we will consider this in the future.
