### ISSUE TITLE
Use ethereum-cryptography

### ISSUE THREAD

**Issue by frangio** [MetaMask/eth-sig-util#110]
This project would benefit from using the [ethereum-cryptography](https://github.com/ethereum/js-ethereum-cryptography) package.

>all the cryptographic primitives normally used when developing Javascript/TypeScript applications and tools for Ethereum

This would fix issues #100 and #72.

https://github.com/MetaMask/eth-sig-util/issues/105 is related. This will be the implementation used in ethereum-cryptography eventually, see https://github.com/ethereum/js-ethereum-cryptography/issues/5.

**Comment by Gudahtt** [comment]
This project now uses `ethereum-cryptography` indirectly via `ethereumjs-util@6`, which we're using as of #195.
