### ISSUE TITLE
Cannot process "bytes" data type

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/eth-sig-util#14]
Need to add test & ensure we can sign bytes, as reported here:
https://github.com/MetaMask/metamask-plugin/issues/2826

**Comment by danfinlay** [comment]
@ukstv Is that user misusing the method, or is this a bug?

**Comment by ukstv** [comment]
@danfinlay Just got an email about that. Please, give me some time to figure out what is wrong.

**Comment by ukstv** [comment]
That is a bug indeed. Fix is in https://github.com/MetaMask/eth-sig-util/pull/15

**Comment by danfinlay** [comment]
Thanks a ton!
