### ISSUE TITLE
Include original .ts files in the NPM package to allow proper debugging

### ISSUE THREAD

**Issue by gabmontes** [MetaMask/eth-sig-util#142]
The published package in NPM only contains the `/dist/*` files but when debugging with i.e. the Chrome DevTools and stepping into the library, an error is thrown because the original `/src/index.ts` file cannot be found and therefore the sourcemaps can't be used to display the proper source lines being executed.

Please update the NPM package to also include the `/src` directory.

Note: To workaround this issue, just copied the `/src` file into `node_modules/eth-sig-util` and the DevTools are happy again.

**Comment by Gudahtt** [comment]
Thanks for the suggestion! Would including inline sources solve the issue for you as well? That should be enough to make Chrome DevTools happy. I had been planning on enabling inline sources anyway.
