### ISSUE TITLE
This package is still "eth-sig-util" on npm

### ISSUE THREAD

**Issue by McRain** [MetaMask/eth-sig-util#190]
Link "Available on NPM" ( https://www.npmjs.com/package/@metamask/eth-sig-util ) 404

**Comment by axic** [comment]
While looking at this, it seems @Gudahtt is one of the main authors, and npms brings up this as the top entry: https://www.npmjs.com/package/eth-sig-util

<img width="397" alt="Screenshot" src="https://user-images.githubusercontent.com/20340/134096778-c8eb016c-5816-4a59-949d-ce84a151bad2.png">

This also has other people (like @danfinlay, @kumavis and @rekmarks) from Metamask listed, so perhaps it is indeed the official package?

(And also https://www.npmjs.com/package/@trufflesuite/eth-sig-util which seems to be a fork.)

@Gudahtt can confirm this is the correct package to look at (and perhaps update the readme)?

**Comment by rekmarks** [comment]
@axic thanks for taking the time to research. Sorry for not noticing this issue sooner.

We are _going to_ release this package under the `@metamask` npm org scope, but have yet to do so. The package that's on npm under `eth-sig-util` is the most recently released version of this repository.

I'll rename this issue to something informative and leave it open until we've published the package under the new name.

**Comment by axic** [comment]
> We are going to release this package under the @metamask npm org scope, but have yet to do so. The package that's on npm under eth-sig-util is the most recently released version of this repository.

Ah okay, the confusing part is that the README points to `@metamask/eth-sig-util` 😉

**Comment by Gudahtt** [comment]
The README corresponds to the version of this library under active development. Please see [the most recent git tag](https://github.com/MetaMask/eth-sig-util/tree/v3.0.1) for the README for the latest production version of the library.

**Comment by Gudahtt** [comment]
The new version has just been published as `@metamask/eth-sig-util`: https://www.npmjs.com/package/@metamask/eth-sig-util
