### ISSUE TITLE
Add `encryptMessage` method.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/eth-sig-util#2]
Should match the functionality of `parity_encryptMessage`:

https://github.com/paritytech/parity/wiki/JSONRPC-parity-module#parity_encryptmessage

**Comment by godfreyhobbs** [comment]
Can this be closed?

**Comment by Gudahtt** [comment]
Now that we have the `encrypt` function, I don't think we want to add this anymore. Closing.
