### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by markg85** [MetaMask/eth-sig-util#227]
The output really says it all.

> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'eslint-plugin-jsdoc@36.1.0',
> npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16' },
> npm WARN EBADENGINE   current: { node: 'v17.1.0', npm: '8.2.0' }
> npm WARN EBADENGINE }
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: '@es-joy/jsdoccomment@0.10.8',
> npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16' },
> npm WARN EBADENGINE   current: { node: 'v17.1.0', npm: '8.2.0' }
> npm WARN EBADENGINE }
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm ERR! code 1
> npm ERR! path /home/mark/GitProjects/eth-sig-util/node_modules/@lavamoat/preinstall-always-fail
> npm ERR! command failed
> npm ERR! command sh -c echo "Don't run npm lifecycle scripts by default, whitelist them with @lavamoat/allow-scripts" && exit 1
> npm ERR! Don't run npm lifecycle scripts by default, whitelist them with @lavamoat/allow-scripts
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/mark/.npm/_logs/2021-12-06T23_17_17_896Z-debug-0.log

**Comment by mcmire** [comment]
Hi @markg85, sorry for the late reply on this. Were you able to get this to work? This looks like a Node mismatch issue.

**Comment by markg85** [comment]
Nope, not from the repository.
I modified the files myself to get it working.

Though to be honest, i have no clue anymore in which project i was using this. I can probably find it again if you want to have the modifications. I essentially fixed #100 with that i think.

**Comment by mcmire** [comment]
It'd probably be better if we merged a fix based on a change used in production, so if you no longer need this then I think we can close this! But feel free to reach out if you need this again.
