### ISSUE TITLE
Don't Depend on Github w/o Commit Hash

### ISSUE THREAD

**Issue by fabioberger** [MetaMask/eth-sig-util#23]
Currently, the `ethereumjs-abi` dep for this package is:

```
"ethereumjs-abi": "git+https://github.com/ethereumjs/ethereumjs-abi.git",
```

This is extremely dangerous since if a `ethereumjs` maintainer, pushes a breaking change to `master`, everyone using `eth-sig-utils` will be affected the next time they `npm install` the package.

When pointing to a Github repo, you should alwys specify a git commit hash. This way, no matter what the maintainers do, the library always pulls in the intended version of the dep.

```
"ethereumjs-abi": "git+https://github.com/ethereumjs/ethereumjs-abi.git#00ba8463a7f7a67fcad737ff9c2ebd95643427f7",
```

**Comment by fabioberger** [comment]
Was this addressed @danfinlay?

**Comment by fabioberger** [comment]
Thanks guys!

**Comment by ottodevs** [comment]
This seems to break Travis CI builds:

`npm ERR! Invalid Version: git+https://github.com/ethereumjs/ethereumjs-abi.git#00ba8463a7f7a67fcad737ff9c2ebd95643427f7`
