### ISSUE TITLE
List of different encryption algorithms

### ISSUE THREAD

**Issue by Kattenelvis** [MetaMask/eth-sig-util#230]
Hello, I'm wondering which types of encryption algorithms are implemented in MetaMask. In the example given [here](https://docs.metamask.io/guide/rpc-api.html#encrypting) use "x25519-xsalsa20-poly1305" and I'm wondering if there exists a list of all possible encryption algorithms that are supported by MetaMask.

**Comment by Kattenelvis** [comment]
To make it more clear, I want the full list of potential strings in the file 
@metamask/eth-sig-util/dist/encryption.ts  with the variable "@param options.version - The type of encryption to use." in the encrypt and encryptSafely functions

**Comment by mcmire** [comment]
Hi @Kattenelvis,

Judging by the [code](https://github.com/MetaMask/eth-sig-util/blob/73ace3309bf4b97d901fb66cd61db15eede7afe9/src/encryption.ts#L39-L79), we only support `x25519-xsalsa20-poly1305` at the moment.

**Comment by Kattenelvis** [comment]
Ahh I see, thank you

**Comment by mcmire** [comment]
No problem!
