### ISSUE TITLE
"Invalid Encoding"

### ISSUE THREAD

**Issue by Kattenelvis** [MetaMask/eth-sig-util#235]
This function
`const decryptedMessege = decryptSafely({
        encryptedData: {ciphertext: validator.data, version:"x25519-xsalsa20-poly1305", ephemPublicKey:validator.publicKey, nonce:"XUYgP2Bgtr4CPZVxTCPzKdSaTyMV7JzUkH7a5msSXxs="},
        privateKey: validator.privateKey
      })`

Leads to an "invalid encoding" error. I tracked it down to this piece of code:

`  function validateBase64(s) {
    if (!(/^(?:[A-Za-z0-9+\/]{2}[A-Za-z0-9+\/]{2})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.test(s))) {
      throw new TypeError('invalid encoding');
    }
  }`

And this appears to happen when s=validator.pubilcKey. That is to say, MetaMask public keys such as my own "0x3b89aC05D2d53f3775697B5Dbc75d8852E740403" is not valid according to the regex. If I remove the "0x" at the start it works but I instead get "bad public key size" error instead. So I don't know what to do here.

**Comment by mcmire** [comment]
Also, I'm not sure the way you're calling `decryptSafely` is correct. You see an example of how it should be called here: https://github.com/MetaMask/eth-sig-util/blob/73ace3309bf4b97d901fb66cd61db15eede7afe9/src/encryption.test.ts#L61-L74

**Comment by Kattenelvis** [comment]
> Public keys are base64-encoded. `0x3b89aC05D2d53f3775697B5Dbc75d8852E740403` looks to me like an address encoded as a 0x-prefixed hex string. You can see an example of what public and private keys would look like here:
> 
> https://github.com/MetaMask/eth-sig-util/blob/73ace3309bf4b97d901fb66cd61db15eede7afe9/src/encryption.test.ts#L10-L15

How do I find my MetaMask public key that looks like that? If I translate the public key over to a base-64 encoding it's too short. 

> Also, I'm not sure the way you're calling `decryptSafely` is correct. You see an example of how it should be called here:
> 
> https://github.com/MetaMask/eth-sig-util/blob/73ace3309bf4b97d901fb66cd61db15eede7afe9/src/encryption.test.ts#L61-L74

Encrypting the data and decrypting the data are done at different parts of the code. But what's proposed here seems to require them to be at the same place.

**Comment by Kattenelvis** [comment]
Ooh right, makes sense. Now I have a similar problem with Nonce, I don't know how to get it to size 24.

**Comment by mcmire** [comment]
Okay. What have you tried so far and what error are you getting?

**Comment by Kattenelvis** [comment]
Since there's no documentation, and googling "nonce" doesn't help, I've really only typed random messages that the regex accepts but I can't get it to accept it and be at length 26 at the same time. An example is "44444444ZZZZ44444444444vj3j44444444=".

**Comment by mcmire** [comment]
According to the documentation for `nacl.box.open`, it will return `null` if authentication fails: https://github.com/dchest/tweetnacl-js#naclboxopenbox-nonce-theirpublickey-mysecretkey

**Comment by Gudahtt** [comment]
Closing as it doesn't appear that this is due to a bug. Feel free to continue asking for help in this thread and we'll help if we get time.
