### ISSUE TITLE
Problem testing sigUtil.recoverTypedSignature

### ISSUE THREAD

**Issue by sullof** [MetaMask/eth-sig-util#24]
I am trying to test an implementation of this
https://medium.com/metamask/scaling-web3-with-signtypeddata-91d6efc8b290
starting from your tests for `eth-sig-util` at
https://github.com/MetaMask/eth-sig-util/blob/master/test/index.js

The problem is that you test `sigUtil.recoverTypedSignatureLegacy`, but not `sigUtil.recoverTypedSignature`.

If I try to test the former, signing the string with `sigUtil.signTypedDataLegacy`, it fails during the execution of `sigUtil.recoverTypedSignature`. If instead, I sign the string with `sigUtil.signTypedData`, it fails during its execution.

It would be good if you add a test for `sigUtil.recoverTypedSignature` and `sigUtil.recoverTypedSignature`.

Anyway, which is the right way to sign a string with `sigUtil` so that the address can be recovered using `sigUtil.recoverTypedSignature`?

Thanks.

**Comment by sullof** [comment]
@danfinlay Any help?

**Comment by rmeissner** [comment]
@sullof just started looking into this project, but from what I tried you should use `sigUtil.recoverTypedSignature({ sig: signature, data: typedData })` to recover the signer address.

You can easily test that by adjusting the last test:
1. `t.plan(8)` -> `t.plan(9)`
1. Add `t.equal(sigUtil.recoverTypedSignature({ sig: sig, data: typedData }), ethUtil.bufferToHex(address))` in the end

**Comment by sullof** [comment]
Thanks. I will try.

**Comment by Gudahtt** [comment]
Thanks for answering the question @rmeissner ! :raised_hands: 

I'll close this for now. Please feel free to post again if you're having issues @sullof . Sorry for the delay in replying.
