### ISSUE TITLE
Confusing terminology: TypedDataUtils.sign() actually hashes data

### ISSUE THREAD

**Issue by weijiekoh** [MetaMask/eth-sig-util#27]
`TypedDataUtils.sign()` is really helpful for hashing data as per the EIP712 standard, but it might be better to give it a clearer name instead of `sign`. Since it functions more like a hash function, instead of a cryptographic signing function, perhaps name it `hash`, `eip712Hash`, or something else instead?

```
  /**
   * Signs a typed message as per EIP-712 and returns its sha3 hash
   *
   * @param {Object} typedData - Types message data to sign 
   * @returns {string} - sha3 hash of the resulting signed message
   */
```

https://github.com/MetaMask/eth-sig-util/blob/master/index.js#L145

**Comment by GFours** [comment]
> `TypedDataUtils.sign()` is really helpful for hashing data as per the EIP712 standard, but it might be better to give it a clearer name instead of `sign`. Since it functions more like a hash function, instead of a cryptographic signing function, perhaps name it `hash`, `eip712Hash`, or something else instead?
> 
> ```
>   /**
>    * Signs a typed message as per EIP-712 and returns its sha3 hash
>    *
>    * @param {Object} typedData - Types message data to sign 
>    * @returns {string} - sha3 hash of the resulting signed message
>    */
> ```
> 
> https://github.com/MetaMask/eth-sig-util/blob/master/index.js#L145

**Comment by weijiekoh** [comment]
> > https://github.com/MetaMask/eth-sig-util/blob/master/index.js#L145

This link gives a 404 error.

**Comment by ashwinYardi** [comment]
Hi @weijiekoh 

Here is the link to the function definition: 
https://github.com/MetaMask/eth-sig-util/blob/9f281f07b7dd36b0572b41bbdbd5b021ec3e3c5b/index.ts#L259

Here is the PR:
https://github.com/MetaMask/eth-sig-util/pull/104

**Comment by Gudahtt** [comment]
Thanks for the suggestion! This was done in #104
