### ISSUE TITLE
Dead line of type code?

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/eth-sig-util#295]
I don't see us use the `EIP712Domain` property anywhere, I think it's outdated code. Can we remove this line for simplicity?
https://github.com/MetaMask/eth-sig-util/blob/554420a9bef69fd4307ad7a762fe81f875e57c76/src/sign-typed-data.ts#L60

**Comment by Gudahtt** [comment]
That is a required property of the `MessageTypes` interface, which is used in a few places. `EIP712Domain` is a required property in EIP-712. Our "input sanitization" will initialize that property if it's not set on the message being signed.

**Comment by danfinlay** [comment]
Hmm. I almost think it would be safer to throw if it’s not provided, but not worth breaking over probably…
