### ISSUE TITLE
what's the purpose?

### ISSUE THREAD

**Issue by amazingandyyy** [MetaMask/eth-sig-util#30]
What's the purpose to use `ethUtil.stripHexPrefix` and `ethUtil.intToHex` at the same time?

Isn't it duplicated?

https://github.com/MetaMask/eth-sig-util/blob/2790801f822f49b87eff635d9f11132f64ab57a8/index.js#L169

**Comment by cag** [comment]
No:

`intToHex` takes a number and turns it into a string containing its hexadecimal representation.

`stripHexPrefix` then takes a hexadecimal string and removes `0x` from the beginning if it starts with that.
