### ISSUE TITLE
recoverTypedSignature(): Cannot read property 'EIP712Domain' of undefined

### ISSUE THREAD

**Issue by n-kort** [MetaMask/eth-sig-util#38]
Presumably related to this https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md

**Comment by MTonomy-Nchinda-Nchinda** [comment]
I can also confirm version 1.4.2 works fine

**Comment by danfinlay** [comment]
I believe you've encountered the difference between `signTypedData_v1` and `signTypedData_v3`, as we document here: https://metamask.github.io/metamask-docs/API_Reference/Signing_Data/Introduction

Sorry for the slow reply, let me know if this isn't the right answer and we can re-open.
