### ISSUE TITLE
recoverTypedSignature incompatible with EIP712

### ISSUE THREAD

**Issue by allegramarie** [MetaMask/eth-sig-util#41]
Hi, I'm upgrading to eth_signedTypedData_v3 (via https://medium.com/metamask/eip712-is-coming-what-to-expect-and-how-to-use-it-bb92fd1a7a26) and finding that recoverTypedSignature is expecting a different data structure than is specified in the new standard. Is there a plan to update this?

**Comment by Gudahtt** [comment]
Thanks for the report, and sorry for the delay in replying! But unfortunately I'm not sure what difference you're referring to, so I'm going to close this for now. Note that the exact function signature for `recoverTypedSignature` is not set in any EIP/standard. The data structure for the message itself expected by `recoverTypedSignature` should match the spec at this time, though it may not have when you originally reported this.
