### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by mishell-trickster** [MetaMask/eth-sig-util#53]
When I try to send a large number (ether field) for a signature, I get an error Assertion failed

`var message = {
		user: "0x000000000000000000",
		ether: 100000000000000000,
		expire: 1559257200
	};`

How to avoid this? I need pass a Wei value with signed message.

**Comment by rekmarks** [comment]
For posterity: the number `100000000000000000` is greater than `Number.MAX_SAFE_INTEGER`. Provide the number as a hexadecimal string instead, and the problem should go away.

@mishell-trickster, my apologies for the delayed response.
