### ISSUE TITLE
signTypedData signs data twice

### ISSUE THREAD

**Issue by aakilfernandes** [MetaMask/eth-sig-util#65]
https://github.com/MetaMask/eth-sig-util/blob/master/index.js#L438-L442

````
  signTypedData: function (privateKey, msgParams) {
    const message = TypedDataUtils.sign(msgParams.data, false)
    const sig = ethUtil.ecsign(message, privateKey)
    return ethUtil.bufferToHex(this.concatSig(sig.v, sig.r, sig.s))
  },
````

Maybe I'm misunderstanding something, but it looks like the data is getting signed twice. The variable `message` is actually the hash of a signature, then ecSign is used to sign it again

**Comment by aakilfernandes** [comment]
Hmm, TypedDataUtils.sign isn't actually passed a private key.... so I assume `sign` doesnt actually sign anything? Looks like its just getting a hash

**Comment by bstchow** [comment]
@aakilfernandes I had a similar misunderstanding of this snippet. I found https://github.com/MetaMask/eth-sig-util/issues/27
 to be helpful in clarifying what's going on in the snippet.
It seems like `TypedDataUtils.sign` isn't actually signing, but is hashing data according to the EIP712 spec.

**Comment by Gudahtt** [comment]
Thanks for explaining @bstchow  - you are exactly right.

I'll close this now, since the question has been answered.
