### ISSUE TITLE
Installation on Node 12 fails

### ISSUE THREAD

**Issue by jtrein** [MetaMask/eth-sig-util#72]
I have experienced an error and issue very similar to this: https://github.com/ethereum/web3.js/issues/3151

I am wondering if it has something to do with `ethereumjs-util`?

**Removing `eth-sig-util` from my project fixed/alleviated this.** I also tried updating to the latest stable version, but it did not help.

```
Node: v12.13.1
npm: 6.12.1
Darwin mac 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
```

**Comment by Gudahtt** [comment]
Thanks for the report! This was fixed in #96
