### ISSUE TITLE
Signing Verification appears to behave differently in browser than in NodeJS v12

### ISSUE THREAD

**Issue by pmumby** [MetaMask/eth-sig-util#85]
Currently I have a use-case for an off-chain application to verify ownership of an address (specifically a Discord Bot).

In this use-case, the bot gathers some parameters, sends the user to the URL of a webpage running a pure JS dapp which uses Metamask to sign a message. It then gives them a string to paste back into the bot, which the bot uses via the same JS code on the back-end to verify the signature.

When I do this, in the browser my code generates the message from 4 parameters, id, name, datestamp, and address.

When I pass those parameters to this code in browser, and sign, metamask pops up, everything looks good, signature works, and the verification code is able to verify the signature is valid just fine.

When I take the same signature, and same parameters and pass it to the exact same code running on NodeJS v12, the verification fails. The address it recovers is completely different.

I've attempted this with the Personal.sign, signTyped, and signTypedV3, all behave the same.

It is expected the behavior of the off-chain verification code would be the same regardless of which JS runtime it's executing in.

The following is code which reproduces the issue for me:
```
const Signer = {
    EIP712DomainSchema: [
        { name: "name", type: "string" },
        { name: "version", type: "string" },
        { name: "salt", type: "bytes32" },
    ],
    DiscordAuthorizationSchema: [
        { name: "statement", type: "string" },
        { name: "id", type: "uint256" },
        { name: "name", type: "string" },
        { name: "date", type: "string" },
        { name: "address", type: "address" },
    ],
    domainData: {
        name: "Discord Address Authorization",
        version: "1.0",
        salt: "0xe2d857f4a3edcb9b78b4d503120433db1e3f6cdc2b7971ab739626c97e86a558"
    },
    buildStatementString: function (id, name, date, address) {
        return (
            "I Hereby verify that I am the owner of the Ethereum Address: " + address + "\n" +
            "I authorize the use of this address by the Discord User ID: " + id + " Named: " + name + "\n" +
            "Signed on Date: " + date
        )
    },
    buildMessageData: function (id, name, date, address) {
        return {
            statement: this.buildStatementString(id, name, date, address),
            id: id,
            name: name,
            date: date,
            address: address
        }
    },
    buildSigningPacket: function (id, name, date, address) {
        return JSON.stringify({
            types: {
                EIP712Domain: this.EIP712DomainSchema,
                DiscordAuthorization: this.DiscordAuthorizationSchema
            },
            domain: this.domainData,
            primaryType: "DiscordAuthorization",
            message: this.buildMessageData(id, name, date, address)
        })
    },
    sign: function (provider, id, name, date, address, callback) {
        provider.sendAsync({
            method: "eth_signTypedData_v3",
            params: [address, this.buildSigningPacket(id, name, date, address)],
            from: address
        }, callback)
    },
    verify: function (signature, id, name, date, address) {
        var ethUtil = require('ethereumjs-util')
        var sigUtil = require('eth-sig-util')
        let recoveryParameters = { data: JSON.parse(this.buildSigningPacket(id, name, date, address)), sig: signature }
        //console.log("RecoveryParameters:" + JSON.stringify(recoveryParameters))
        let recovered = sigUtil.recoverTypedSignature(recoveryParameters)
        let expectedAddress = ethUtil.toChecksumAddress(address)
        let recoveredAddress = ethUtil.toChecksumAddress(recovered)
        console.log("Expected Address:" + expectedAddress)
        console.log("Recovered Address:" + recoveredAddress)
        return expectedAddress === recoveredAddress
    }
}
```

I am using the following versions:
NodeJS 12.16.1
eth-sig-util 2.5.3

Any help or recommendations would be greatly appreciated!

Thanks!

**Comment by kumavis** [comment]
@pmumby can you help us reproduce this?
can you provide some signature parameters?

**Comment by pmumby** [comment]
@kumavis I can certainly try to help reproduce. The above js code is exactly the code I'm using. But I realize I may have left some context out:

First in my code I'm calling the sign method with the following:
Signer.sign(window.web3.currentProvider, id, name, date, address, callback)
(of course doing some validation that window.web3 is populated etc)
Pretty much any values for id, name, date, address will re-create the problem from memory.

An example of what these fields might look like:
id = "111103302865551443"
name = "PickAUserName"
date = "2020-04-27"
address = "0xANYVALIDETHADDRESS"
callback is a function expecting 2 params (err, data)

My test calls this, and in the simple callback checks for err, if so throws with err.message
Otherwise  uses Signer.verify(data.result, id, name, date, address)

The the verify call should return true.

From a web browser (Chrome specifically) this returns true, all is good.
I also in my test output the values, which I can then paste into a call to the node service, I have that service output in it's log the values it's using so I can ensure the method (discord) isn't doing some fiddling of the values... And it then calls the same method to verify the signature. But from node it fails (returns false).

The only difference I see is the execution environment (chrome vs nodejs). And the fact that in Node there is no web3 (but the verify process does not rely on web3 at all).

It's entirely possible the underlying dependencies may differ slightly on node, but it shouldn't. The same environment/dev machine is used to compile both the react app (built from node, using same instance of NPM to install deps) as the one used to compile the node service.

I suspect there is some underlying behavior in the ethereumjs-util or eth-sig-util packages (or anything in their dependency tree) which uses some behavior which has a minor difference between node/browser js runtimes, resulting in a slightly different result.

The whole process "works" no errors are thrown, but the verify results in a non-match (validates back to a different signing address as opposed to the actual one used to sign)

Does that help? Or do you need me to actually re-create a full project which reproduces the error?

I've since worked around this in my project (by manually doing the signing verification through a human process from an admin pasting the signature back into a new web interface to verify, but that's clunky). But point being would take me a bit to get my code to a place this is easily being re-created, so I'd likely just build an entirely new project just to prove this out (which would require a bit of work).

Let me know if that's sufficient for you to reproduce.

Thanks!

**Comment by kumavis** [comment]
> Does that help? Or do you need me to actually re-create a full project which reproduces the error?

I added browser tests for `eth-sig-util` which I was hoping to tease out an issue but tests passed. Being able to replay your bug would be useful. If you can provide a simple git repo that demonstrates this issue, it would be appreciated. thanks

**Comment by Gudahtt** [comment]
Thanks for the report @pmumby ! But without a reproduction, I'm not sure how to investigate this further.

I'll close the issue for now, but if you manage to reproduce this again I'd be very eager to see how.
