### ISSUE TITLE
ES6 module breaks uglify

### ISSUE THREAD

**Issue by cloudonshore** [MetaMask/eth-sig-util#9]
Hello,
  would you consider publishing an es5 version of the module as `index.js`? Since ProviderEngine depends on this module, if any package in my node modules depends on ProviderEngine it will break a create-react-app's webpack build on it's Uglify step.

  Also, please let me know any way I can help and I'd be happy to open a pull request :)

   (ref of issue: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

**Comment by danfinlay** [comment]
You’re totally welcome to add a PR to transpile out export, I’m surprised I haven’t yet, but may not get to this myself as soon as you’d like it.

**Comment by danfinlay** [comment]
Fixed in `eth-sig-util@1.4.1`.
